version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
environment:
  SolutionDir: $(APPVEYOR_BUILD_FOLDER)\DotNetFloripa
cache:
- packages -> **\packages.config
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore DotNetFloripa/DotNetFloripa.sln
build:
  project: DotNetFloripa/DotNetFloripa.sln
  verbosity: normal